"""update_database_structure

Revision ID: 92f455e765cf
Revises: 747043455a84
Create Date: 2025-06-25 15:48:30.288009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f455e765cf'
down_revision: Union[str, Sequence[str], None] = '747043455a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=True)
    op.drop_index(op.f('ix_urls_id'), table_name='urls')
    op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_urls_id'), table_name='urls')
    op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=False)
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    # ### end Alembic commands ###
